export const GET_LISTINGS = 'GET_LISTINGS';
export const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';
export const GET_LISTINGS_DETAIL_SUCCESS = 'GET_LISTINGS_DETAIL_SUCCESS';
export const GET_META_SUCCESS = 'GET_META_SUCCESS';
